# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 01:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d{2}-\\d{5}-\\d{4}$', 32), 'Informe o CELULAR no formato xx-xxxxx-xxxx', 'invalid')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d{5}-\\d{3}$', 32), 'Informe o CEP no formado xxxxx-xxx.', 'invalid')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d{2}-\\d{4}-\\d{4}$', 32), 'Informe o TELEFONE no formato xx-xxxx-xxxx', 'invalid')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Grupo'),
        ),
    ]
