# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20170306_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Grupo'),
        ),
    ]
