# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20170306_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
