# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 02:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_associado_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='cpf',
            field=models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d{3}.\\d{3}.\\d{3}-\\d{2}$', 32), 'Informe o CPF no formato xxx.xxx.xxx-xx', 'invalid')], verbose_name='CPF'),
        ),
    ]
