# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 05:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20170308_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d{3}.\\d{3}.\\d{3}-\\d{2}$', 32), 'Informe o CPF no formato xxx.xxx.xxx-xx', 'invalid')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
