# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_auto_20170322_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='associado',
            field=models.BooleanField(verbose_name='Contribuinte'),
        ),
    ]
