# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_auto_20170322_1540'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='associadofamilia',
            unique_together=set([('associado', 'familia')]),
        ),
    ]
