# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_auto_20170322_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadofamilia',
            name='associado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Associado', verbose_name='associado'),
        ),
    ]
