# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0009_auto_20170309_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_ref', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(re.compile('^\\d{4}$', 32), 'Informe apenas números.', 'invalid')], verbose_name='Ano Referência')),
                ('data_doc', models.DateTimeField(verbose_name='Data Documento')),
                ('data_ven', models.DateTimeField(verbose_name='Data Vencimento')),
                ('data_pag', models.DateTimeField(null=True, verbose_name='Data Pagamento')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Associado')),
            ],
            options={
                'verbose_name': 'Contas a Receber',
                'verbose_name_plural': 'Contas a Receber',
            },
        ),
    ]
