# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receber',
            name='data_doc',
            field=models.DateField(verbose_name='Data Documento'),
        ),
        migrations.AlterField(
            model_name='receber',
            name='data_pag',
            field=models.DateField(null=True, verbose_name='Data Pagamento'),
        ),
        migrations.AlterField(
            model_name='receber',
            name='data_ven',
            field=models.DateField(verbose_name='Data Vencimento'),
        ),
    ]
