# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20170316_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receber',
            name='data_pag',
            field=models.DateField(blank=True, null=True, verbose_name='Data Pagamento'),
        ),
        migrations.AlterField(
            model_name='receber',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor'),
        ),
    ]
